# Generated by Django 5.1.1 on 2024-09-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
