# Generated by Django 5.1.1 on 2024-09-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_complete_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete_date',
            new_name='completeDate',
        ),
    ]
